<?php
if(UserSession::isUserSignedIn()){
    include("./view/pagecontent/header/content_header_signedin.php");
}else{
    include("./view/pagecontent/header/content_header_signedout.php"); 
}
if(!UserSession::isSessionValid()){
    include_once("./model/actions/model_signout.php");
}
echo('content_header');
?>