<?php 
require_once(ROOT_DIR.'./controller/UserSession.php');
if(UserSession::isUserSignedIn()){
	include(ROOT_DIR.'./view/webcontent/header/header_signedin.php');
}
else{
	include(ROOT_DIR.'./view/webcontent/header/header_signedout.php');
}
?>